formatter: "markdown table"

sections:
  hide:
    - providers
    - resources
    - requirements

recursive:
  enabled: true
  path: modules

output:
  file: README.md
  mode: inject
  
content: |-
  {{ .Header }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}  

  # Your Title

  Your custom information goes here.
