apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-ecs-fargate-cluster
  title: AWS ECS Fargate Cluster
  description: Version control template for Terraform modules with CI files
  links:
    - url: https://pages.github.boozallencsn.com/AutomationLibrary/aws-ecs-fargate-cluster/index.html
      title: Documentation
  annotations:
  ## NOTE: see above
  #   backstage.io/techdocs-ref: dir:.
    github.com/project-slug: AutomationLibrary/aws-ecs-fargate-cluster
  tags:
    - aws
    - terraform
    - ecs
    - fargate
spec:
  type: library
  lifecycle: production
  owner: AutomationLibrary/BrightLabs