formatter: "markdown table"

sections:
  hide:
    - providers
    - resources

output:
  file: ../../docs/source/MODULE_FARGATE.md
  mode: inject

content: |-
  {{ .Header }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}  