#checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"

name: terraform workflows

# see: https://github.com/bridgecrewio/checkov/issues/4127
permissions: write-all

on:
  push:
    branches:
      - feature/**
      - hotfix/**
      # these two branches are included in the template repo to force docs to build on master pushes...
      # they should be removed for projects...
      - master
      - main

  # see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

# NOTE: if the GHES version is ever updated to the latest version, instead of passing the secrets 
#       individually, the `inherit` key word can be used. Until such time, enumerating each secret
#       for the workflow that uses it is required.
# 3.5 docs: https://docs.github.com/en/enterprise-server@3.5/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
# current docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-secrets-to-nested-workflows
jobs:
  Scan:
    if: ${{ github.event_name == 'push' }}
    uses: AutomationLibrary/actions-workflows/.github/workflows/tf-scan.yml@main

  Lint:
    if: ${{ github.event_name == 'push' }}
    uses: AutomationLibrary/actions-workflows/.github/workflows/tf-lint.yml@main

  Docs:
    if: ${{ github.event_name == 'push' }}
    uses: AutomationLibrary/actions-workflows/.github/workflows/gh-pages.yml@main
    secrets:
      ACTIONS_BOT_USERNAME: ${{ secrets.ACTIONS_BOT_USERNAME }}
      ACTIONS_BOT_EMAIL: ${{ secrets.ACTIONS_BOT_EMAIL }}

